import { GoogleAuth } from "google-auth-library";
import fallbackDebate from "@/data/quebec-debate-fallback.json";
import { appEnv } from "@/lib/env";
import type { Debate } from "@/lib/types";

interface VertexCandidateResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
}

export async function generateDebateSeed(): Promise<Debate> {
  try {
    return await generateWithVertex();
  } catch (error) {
    console.error("Falling back to bundled debate seed.", error);
    return structuredClone(fallbackDebate) as Debate;
  }
}

async function generateWithVertex(): Promise<Debate> {
  if (!appEnv.projectId) {
    throw new Error("Missing project id for Vertex generation.");
  }

  const auth = new GoogleAuth({
    scopes: ["https://www.googleapis.com/auth/cloud-platform"],
  });
  const client = await auth.getClient();
  const accessToken = await client.getAccessToken();

  if (!accessToken.token) {
    throw new Error("Unable to obtain Google Cloud access token.");
  }

  const prompt = `
You are preparing the opening arguments for a civic debate platform.
Return strict JSON only and no markdown.

Build a balanced bilingual debate object about: "Should Quebec become a country?"

Requirements:
- Root keys must match this exact shape:
  {
    "seedSource": "vertex",
    "title": { "fr": string, "en": string },
    "question": { "fr": string, "en": string },
    "intro": { "fr": string, "en": string },
    "yesLabel": { "fr": string, "en": string },
    "noLabel": { "fr": string, "en": string },
    "yesArguments": ArgumentCard[],
    "noArguments": ArgumentCard[]
  }
- Each ArgumentCard must contain:
  {
    "id": kebab-case string,
    "title": { "fr": string, "en": string },
    "summary": { "fr": string, "en": string },
    "details": { "fr": string, "en": string }
  }
- Generate exactly 3 arguments for yesArguments and 3 arguments for noArguments.
- Tone must be balanced, civic, and fair-minded.
- Summaries should be concise. Details should be a compact paragraph.
- Do not mention that the content was generated by AI.
`;

  const response = await fetch(
    `https://aiplatform.googleapis.com/v1/projects/${appEnv.projectId}/locations/global/publishers/google/models/gemini-2.5-flash:generateContent`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken.token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          temperature: 0.4,
          responseMimeType: "application/json",
        },
      }),
    },
  );

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Vertex request failed: ${response.status} ${body}`);
  }

  const payload = (await response.json()) as VertexCandidateResponse;
  const text =
    payload.candidates?.[0]?.content?.parts
      ?.map((part) => part.text ?? "")
      .join("")
      .trim() ?? "";

  if (!text) {
    throw new Error("Vertex returned an empty response.");
  }

  const parsed = JSON.parse(text) as Partial<Debate>;

  return {
    ...(structuredClone(fallbackDebate) as Debate),
    ...parsed,
    id: "quebec-country",
    slug: "quebec-country",
    seedSource: "vertex",
    status: "live",
    yesCount: 0,
    noCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
